[[mgr.prepend_keymap]]
# ya pkg add yazi-rs/plugins:smart-enter
# from: https://github.com/yazi-rs/plugins/tree/main/smart-enter.yazi
on   = "l"
run  = "plugin smart-enter"
desc = "Enter the child directory, or open the file"

# ya pkg add yazi-rs/plugins:smart-paste
# from: https://github.com/yazi-rs/plugins/tree/main/smart-paste.yazi
[[mgr.prepend_keymap]]
on   = "p"
run  = "plugin smart-paste"
desc = "Paste into the hovered directory or CWD"

# ya pkg add yazi-rs/plugins:zoom
# from: https://github.com/yazi-rs/plugins/tree/main/zoom.yazi
[[mgr.prepend_keymap]]
on   = "+"
run  = "plugin zoom 1"
desc = "Zoom in hovered file"

[[mgr.prepend_keymap]]
on   = "-"
run  = "plugin zoom -1"
desc = "Zoom out hovered file"
